_target_: pangaea.encoders.tessera_encoder.TesseraEncoder

# n/a for geotessera
encoder_weights: null
download_url: null

input_size: 128
output_layers: [0]
output_dim: 128
input_bands:
  optical: []

# geoTessera specific
cache_dir: ./geotessera_cache  # directory to cache downloaded embeddings




